apiVersion: v2
appVersion: 10.8.5
description: emoncms helm package
name: emoncms
version: 2.1.0
kubeVersion: ">=1.16.0-0"
keywords:
- emoncms
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/emoncms
icon: https://emoncms.org/icon
sources:
- https://github.com/emoncms/emoncms-docker
maintainers:
- name: emoncms
  email: emoncms@emoncms.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.2.0
- name: mariadb
  version: 10.6.5
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
- name: redis
  version: 6.2.6
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
